local control = {}
control.genericParams = {
   { "s", "n", "gain" },
   { "cutoff", "resonance" },
   { "hcutoff", "hresonance" },

   { "delay", "delaytime", "delayfeedback" },
   { "room", "size" },
   { "bandf", "bandq" }, --bpenv
   "toArg",
   "from",
   "to",
   "accelerate",
   "amp",
   "attack",
   "bandq",
   "begin",
   "legato",
   "clhatdecay",
   "crush",
   "coarse",
   "channel",
   "cut",
   "cutoff",
   "cutoffegint",
   "decay",
   "delayfeedback",
   "delaytime",
   "detune",
   "djf",
   "dry",
   "end",
   "fadeTime",
   "fadeInTime",
   "freq",
   "gain",
   "gate",
   "hatgrain",
   "hold",
   "hresonance",
   "lagogo",
   "lclap",
   "lclaves",
   "lclhat",
   "lcrash",
   "leslie",
   "lrate",
   "lfodelay",
   "lfosync",
   "lock",
   "metatune",
   "mtranspose",
   "octaveR",
   "ophatdecay",
   "orbit",
   "pan",
   "panorient",
   "portamento",
   "sagogo",
   "semitone",
   "speed",
   "sustain",
   "unit",
   "voice",
   "vowel",
   "modwheel",
   "tremolorate",
   "fshiftnote",
   "kcutoff",
   "octer",
   "octersub",
   "octersubsub",
   "ring",
   "ringf",
   "ringdf",
   "distort",
   "freeze",
   "xsdelay",
   "tsdelay",
   "real",
   "imag",
   "enhance",
   "partials",
   "comb",
   "smear",
   "scram",
   "binshift",
   "hbrick",
   "lbrick",
}

control.aliasParams = {
   s = "sound",
   note = "up",
   attack = "att",
   bandf = "bpf",
   bandq = "bpq",
   clhatdecay = "chdecay",
   cutoff = { "ctf", "lpf" },
   cutoffegint = "ctfg",
   delayfeedback = { "dfb", "delayfb" },
   delaytime = { "dt", "delayt" },
   detune = "det",
   fadeTime = "fadeOutTime",
   gate = "gat",
   hatgrain = "hg",
   hcutoff = "hpf",
   hresonance = "hpq",
   lagogo = "lag",
   lkick = "lbd",
   lclhat = "lch",
   lclaves = "lcl",
   lclap = "lcp",
   lcrash = "lcr",
   lfocutoffint = "lfoc",
   lfoint = "lfoi",
   lfopitchint = "lfop",
   lhitom = "lht",
   llotom = "llt",
   lophat = "loh",
   resonance = "lpq",
   lsnare = "lsn",
   n = "number",
   ophatdecay = "ohdecay",
   phaserdepth = "phasdp",
   phaserrate = "phasr",
   pitch1 = "pit1",
   pitch2 = "pit2",
   pitch3 = "pit3",
   portamento = "por",
   release = "rel",
   sagogo = "sag",
   sclaves = "scl",
   sclap = "scp",
   scrash = "scr",
   size = "sz",
   slide = "sld",
   stutterdepth = "std",
   stuttertime = "stt",
   sustain = "sus",
   tomdecay = "tdecay",
   tremolodepth = "tremdp",
   tremolorate = "tremr",
   vcfegint = "vcf",
   vcoegint = "vco",
   voice = "voi",
}

return control
