name: docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.1.5
    - uses: leafo/gh-actions-luarocks@v4
    - name: build
      run: luarocks install ldoc
    - name: generate
      run: ldoc .
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
